### ISSUE TITLE
Realistic Money Interactions

### ISSUE THREAD

**Issue by Camnewb** [WHSTSALibrary2017/Library#38]
I don't think this application needs to track the wallets of each member, and the fine system should mainly be for tracking the amount a member owes, not whether or not they can pay it. This can be easily solved by making a single static method that fills the member's wallet with the necessary money, but for DayGenerator this may have wider implications.

**Comment by EricRabil** [comment]
I agree with you 100% that we don't need to track wallets. I'll start
removing it and just have the fines portion of it
