### ISSUE TITLE
StatusBar is blank

### ISSUE THREAD

**Issue by Camnewb** [WHSTSALibrary2017/Library#41]
A result of the new BackgroundWorker system.

**Comment by EricRabil** [comment]
Do you mean the tool tips are broken? The only thing that relies on the
background worker is the tooltip that says whether the date is not accurate.

**Comment by Camnewb** [comment]
I changed the live status method to use Background worker as well, assuming you just didn't have time to in class. Either way neither the date or status show in the bar, and I get an exception when I run it. I can revert my changes if you intended to not use BackgroundWorker for the saved status.

**Comment by EricRabil** [comment]
In my latest commit this issue is fixed. I've tested it. Have you fully
pulled and cleaned your local git repo?

**Comment by Camnewb** [comment]
Yeah that's my bad, I forgot to build before running it. Issue is fixed on my end
