### ISSUE TITLE
Checkin view regression; completely unexpected behavior

### ISSUE THREAD

**Issue by EricRabil** [WHSTSALibrary2017/Library#50]
Return dialog returns books regardless of overdue state; it does not properly return books and as a result simply extends the due date.

**Planned course of action:** Refactor of the checkin/checkout views.

**Comment by nullpixel** [comment]
This is why unit tests exist, Eric.

**Comment by EricRabil** [comment]
@nullpixel we're planning on adding unit tests in the future if time permits.

**Comment by AppleBetas** [comment]
Check-in*
